name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint (black + ruff)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --with=dev

      - name: Run black
        run: poetry run black --check .

      - name: Run ruff
        run: poetry run ruff check .

  test:
    name: Pytest ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --with=dev

      - name: Run tests
        run: poetry run pytest
